version: "3.8"

services:
  carbone:
    image: carbone/carbone-ee:full
    container_name: carbone
    ports:
      - "4000:4000"            # снаружи будет http://localhost:4000
    environment:
      # Отключаем auth для локальной песочницы
      CARBONE_SECRET_KEY: "dev-secret-key"
      CARBONE_ALLOW_HTTP: "true"
      CARBONE_HTTP_PORT: "4000"
      # Логи по желанию
      CARBONE_LOG_LEVEL: "info"
    volumes:
      - ./trial.carbone-license:/app/config/trial.carbone-license
      - ./config.json:/app/config/config.json
